language: python
os: linux
sudo: required
dist: bionic

addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libopenmpi-dev
            - openmpi-bin

python:
    - 3.8
notifications:
    email: false

before_install:
    - pip install future # nedded for caput setup
    - pip install Cython # needed for cora setup

install:
    - pip install -r .requirements-travis.txt
    - pip install .

script:
    # Run black on all .py files in all subfolders
    - black --check .

    # TODO:
    # Run pydocstyle on all .py files
    # - find . -name \*.py -exec pydocstyle --convention=numpy --add-ignore=D105,D202 {} +

    # Build docs
    - cd doc
    - make html
    - cd ..
