name: ch-pipeline-ci-build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:

  lint-code:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install pip dependencies
      run: pip install black ruff

    - name: Run Ruff
      run: ruff check .

    - name: Check code with black
      run: black --check .

  install-build-docs:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install apt dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libopenmpi-dev openmpi-bin libhdf5-serial-dev

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install requirements
      run: pip install .[docs]

    - name: Build sphinx docs
      run: sphinx-build -W -b html doc/ doc/_build/html
